enum EventType {
  LOGIN,
  SET_AUTH_USER,
  LOGOUT,
  JOIN_GROUP,
  RECEIVE_GROUP_MESSAGE,
  MEMBER_JOIN_GROUP,
  MEMBER_LEAVE_GROUP,
  MEMBER_MARK_AS_READ,
  SWITCH_CHATROOM,
}

export default EventType;
